services:
  postgres:
    image: postgres:16-alpine
    container_name: internovayz_db
    environment:
      POSTGRES_USER: internova
      POSTGRES_PASSWORD: internova
      POSTGRES_DB: internova_yz
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U internova -d internova_yz"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: internovayz_redis
    ports:
      - "6379:6379"

volumes:
  postgres_data:
