"""portfolios teknoloji_puanlari alani

Revision ID: 09717c3aa89e
Revises: 84d263889334
Create Date: 2026-05-21 16:30:06.967293

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '09717c3aa89e'
down_revision: Union[str, Sequence[str], None] = '84d263889334'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('portfolios', sa.Column('teknoloji_puanlari', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('portfolios', 'teknoloji_puanlari')
    # ### end Alembic commands ###
