"""portfolios proje_buyuklugu alani

Revision ID: 0d8d50cc942a
Revises: 09717c3aa89e
Create Date: 2026-05-21 16:38:21.883022

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d8d50cc942a'
down_revision: Union[str, Sequence[str], None] = '09717c3aa89e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('portfolios', sa.Column('proje_buyuklugu', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('portfolios', 'proje_buyuklugu')
    # ### end Alembic commands ###
