"""portfolios teknoloji_degerleri alani

Revision ID: 341dd0826186
Revises: 0d8d50cc942a
Create Date: 2026-05-21 17:03:37.614338

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '341dd0826186'
down_revision: Union[str, Sequence[str], None] = '0d8d50cc942a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('portfolios', sa.Column('teknoloji_degerleri', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('portfolios', 'teknoloji_degerleri')
    # ### end Alembic commands ###
