"""portfolios konu teknik_yetkinlik beceriler

Revision ID: 841e5ff18ab0
Revises: 341dd0826186
Create Date: 2026-05-21 17:20:09.516315

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '841e5ff18ab0'
down_revision: Union[str, Sequence[str], None] = '341dd0826186'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('portfolios', sa.Column('konu', sa.String(length=500), nullable=True))
    op.add_column('portfolios', sa.Column('teknik_yetkinlik', sa.Float(), nullable=True))
    op.add_column('portfolios', sa.Column('beceriler', sa.Float(), nullable=True))
    op.drop_column('portfolios', 'teknoloji_puanlari')
    op.drop_column('portfolios', 'teknoloji_degerleri')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('portfolios', sa.Column('teknoloji_degerleri', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('portfolios', sa.Column('teknoloji_puanlari', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('portfolios', 'beceriler')
    op.drop_column('portfolios', 'teknik_yetkinlik')
    op.drop_column('portfolios', 'konu')
    # ### end Alembic commands ###
