"""internships bolum_kodu alani

Revision ID: 84d263889334
Revises: aac7d721d704
Create Date: 2026-05-21 15:02:46.719003

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '84d263889334'
down_revision: Union[str, Sequence[str], None] = 'aac7d721d704'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('internships', sa.Column('bolum_kodu', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('internships', 'bolum_kodu')
    # ### end Alembic commands ###
