"""portfolios analiz_durumu

Revision ID: 8d3b60982822
Revises: 841e5ff18ab0
Create Date: 2026-05-21 17:49:31.358264

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d3b60982822'
down_revision: Union[str, Sequence[str], None] = '841e5ff18ab0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('portfolios', sa.Column('analiz_durumu', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('portfolios', 'analiz_durumu')
    # ### end Alembic commands ###
