"""users bolum_kodu alani

Revision ID: aac7d721d704
Revises: f85af9d89381
Create Date: 2026-05-21 14:08:14.400863

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aac7d721d704'
down_revision: Union[str, Sequence[str], None] = 'f85af9d89381'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('bolum_kodu', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'bolum_kodu')
    # ### end Alembic commands ###
