"""initial schema with all tables

Revision ID: cabffb7c6683
Revises: 
Create Date: 2026-05-20 21:31:23.530534

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cabffb7c6683'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('badges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ad', sa.String(length=200), nullable=False),
    sa.Column('aciklama', sa.Text(), nullable=True),
    sa.Column('ikon_url', sa.String(length=500), nullable=True),
    sa.Column('kategori', sa.String(length=100), nullable=True),
    sa.Column('kazanma_kurali', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ad')
    )
    op.create_index(op.f('ix_badges_id'), 'badges', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('student', 'teacher', 'company', name='userrole'), nullable=False),
    sa.Column('ad', sa.String(length=100), nullable=False),
    sa.Column('soyad', sa.String(length=100), nullable=False),
    sa.Column('bolum', sa.String(length=200), nullable=True),
    sa.Column('ogrenci_no', sa.String(length=50), nullable=True),
    sa.Column('telefon', sa.String(length=20), nullable=True),
    sa.Column('profil_foto_url', sa.String(length=500), nullable=True),
    sa.Column('email_dogrulandi', sa.Boolean(), nullable=False),
    sa.Column('aktif', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('certificates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('ad', sa.String(length=300), nullable=False),
    sa.Column('veren_kurum', sa.String(length=300), nullable=True),
    sa.Column('tarih', sa.Date(), nullable=True),
    sa.Column('dosya_url', sa.String(length=500), nullable=True),
    sa.Column('ocr_metin', sa.Text(), nullable=True),
    sa.Column('dogrulanmis', sa.Boolean(), nullable=False),
    sa.Column('ocr_skoru', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_certificates_id'), 'certificates', ['id'], unique=False)
    op.create_index(op.f('ix_certificates_student_id'), 'certificates', ['student_id'], unique=False)
    op.create_table('cvs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('ozet', sa.Text(), nullable=True),
    sa.Column('egitim', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('deneyim', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('beceriler', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('diller', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id')
    )
    op.create_index(op.f('ix_cvs_id'), 'cvs', ['id'], unique=False)
    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organizator_id', sa.Integer(), nullable=False),
    sa.Column('baslik', sa.String(length=300), nullable=False),
    sa.Column('aciklama', sa.Text(), nullable=True),
    sa.Column('kategori', sa.Enum('panel', 'gezi', 'workshop', 'konferans', 'diger', name='eventcategory'), nullable=False),
    sa.Column('baslangic_tarihi', sa.DateTime(timezone=True), nullable=False),
    sa.Column('bitis_tarihi', sa.DateTime(timezone=True), nullable=True),
    sa.Column('konum', sa.String(length=300), nullable=True),
    sa.Column('kapasite', sa.Integer(), nullable=True),
    sa.Column('qr_kod', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organizator_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('qr_kod')
    )
    op.create_index(op.f('ix_events_id'), 'events', ['id'], unique=False)
    op.create_index(op.f('ix_events_organizator_id'), 'events', ['organizator_id'], unique=False)
    op.create_table('internships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('pozisyon', sa.String(length=200), nullable=False),
    sa.Column('departman', sa.String(length=200), nullable=True),
    sa.Column('konum', sa.String(length=200), nullable=True),
    sa.Column('aciklama', sa.Text(), nullable=True),
    sa.Column('gereksinimler', sa.Text(), nullable=True),
    sa.Column('kontenjan', sa.Integer(), nullable=True),
    sa.Column('basvuru_son_tarih', sa.Date(), nullable=True),
    sa.Column('staj_baslangic', sa.Date(), nullable=True),
    sa.Column('staj_bitis', sa.Date(), nullable=True),
    sa.Column('ucret_var_mi', sa.Boolean(), nullable=False),
    sa.Column('durum', sa.Enum('aktif', 'kapali', 'taslak', name='internshipstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_internships_company_id'), 'internships', ['company_id'], unique=False)
    op.create_index(op.f('ix_internships_id'), 'internships', ['id'], unique=False)
    op.create_table('portfolios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('proje_adi', sa.String(length=300), nullable=False),
    sa.Column('aciklama', sa.Text(), nullable=True),
    sa.Column('github_link', sa.String(length=500), nullable=True),
    sa.Column('demo_link', sa.String(length=500), nullable=True),
    sa.Column('teknolojiler', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('gorseller', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_portfolios_id'), 'portfolios', ['id'], unique=False)
    op.create_index(op.f('ix_portfolios_student_id'), 'portfolios', ['student_id'], unique=False)
    op.create_table('project_teams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lider_id', sa.Integer(), nullable=False),
    sa.Column('proje_adi', sa.String(length=300), nullable=False),
    sa.Column('aciklama', sa.Text(), nullable=True),
    sa.Column('aranan_yetkinlikler', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('max_uye_sayisi', sa.Integer(), nullable=True),
    sa.Column('durum', sa.Enum('acik', 'dolu', 'tamamlandi', name='teamstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['lider_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_teams_id'), 'project_teams', ['id'], unique=False)
    op.create_index(op.f('ix_project_teams_lider_id'), 'project_teams', ['lider_id'], unique=False)
    op.create_table('user_badges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('badge_id', sa.Integer(), nullable=False),
    sa.Column('kazanma_tarihi', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['badge_id'], ['badges.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'badge_id', name='uq_user_badge')
    )
    op.create_index(op.f('ix_user_badges_badge_id'), 'user_badges', ['badge_id'], unique=False)
    op.create_index(op.f('ix_user_badges_id'), 'user_badges', ['id'], unique=False)
    op.create_index(op.f('ix_user_badges_user_id'), 'user_badges', ['user_id'], unique=False)
    op.create_table('applications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('internship_id', sa.Integer(), nullable=False),
    sa.Column('durum', sa.Enum('bekleyen', 'kabul', 'red', name='applicationstatus'), nullable=False),
    sa.Column('basvuru_tarihi', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('karar_tarihi', sa.DateTime(timezone=True), nullable=True),
    sa.Column('on_yazi', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['internship_id'], ['internships.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'internship_id', name='uq_application_student_internship')
    )
    op.create_index(op.f('ix_applications_id'), 'applications', ['id'], unique=False)
    op.create_index(op.f('ix_applications_internship_id'), 'applications', ['internship_id'], unique=False)
    op.create_index(op.f('ix_applications_student_id'), 'applications', ['student_id'], unique=False)
    op.create_table('diary_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('internship_id', sa.Integer(), nullable=False),
    sa.Column('tarih', sa.Date(), nullable=False),
    sa.Column('ham_metin', sa.Text(), nullable=True),
    sa.Column('akademik_metin', sa.Text(), nullable=True),
    sa.Column('llm_isleme_durumu', sa.Enum('bekliyor', 'tamamlandi', 'hata', name='llmprocessingstatus'), nullable=False),
    sa.Column('onaylandi', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['internship_id'], ['internships.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_diary_entries_id'), 'diary_entries', ['id'], unique=False)
    op.create_index(op.f('ix_diary_entries_internship_id'), 'diary_entries', ['internship_id'], unique=False)
    op.create_index(op.f('ix_diary_entries_student_id'), 'diary_entries', ['student_id'], unique=False)
    op.create_table('event_attendees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('katilim_zamani', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id', 'user_id', name='uq_event_attendee')
    )
    op.create_index(op.f('ix_event_attendees_event_id'), 'event_attendees', ['event_id'], unique=False)
    op.create_index(op.f('ix_event_attendees_id'), 'event_attendees', ['id'], unique=False)
    op.create_index(op.f('ix_event_attendees_user_id'), 'event_attendees', ['user_id'], unique=False)
    op.create_table('team_applications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('applicant_id', sa.Integer(), nullable=False),
    sa.Column('mesaj', sa.Text(), nullable=True),
    sa.Column('durum', sa.Enum('bekleyen', 'kabul', 'red', name='teamapplicationstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['applicant_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['project_teams.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_team_applications_applicant_id'), 'team_applications', ['applicant_id'], unique=False)
    op.create_index(op.f('ix_team_applications_id'), 'team_applications', ['id'], unique=False)
    op.create_index(op.f('ix_team_applications_team_id'), 'team_applications', ['team_id'], unique=False)
    op.create_table('team_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('rol', sa.String(length=100), nullable=True),
    sa.Column('katilim_tarihi', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['project_teams.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('team_id', 'user_id', name='uq_team_member')
    )
    op.create_index(op.f('ix_team_members_id'), 'team_members', ['id'], unique=False)
    op.create_index(op.f('ix_team_members_team_id'), 'team_members', ['team_id'], unique=False)
    op.create_index(op.f('ix_team_members_user_id'), 'team_members', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_team_members_user_id'), table_name='team_members')
    op.drop_index(op.f('ix_team_members_team_id'), table_name='team_members')
    op.drop_index(op.f('ix_team_members_id'), table_name='team_members')
    op.drop_table('team_members')
    op.drop_index(op.f('ix_team_applications_team_id'), table_name='team_applications')
    op.drop_index(op.f('ix_team_applications_id'), table_name='team_applications')
    op.drop_index(op.f('ix_team_applications_applicant_id'), table_name='team_applications')
    op.drop_table('team_applications')
    op.drop_index(op.f('ix_event_attendees_user_id'), table_name='event_attendees')
    op.drop_index(op.f('ix_event_attendees_id'), table_name='event_attendees')
    op.drop_index(op.f('ix_event_attendees_event_id'), table_name='event_attendees')
    op.drop_table('event_attendees')
    op.drop_index(op.f('ix_diary_entries_student_id'), table_name='diary_entries')
    op.drop_index(op.f('ix_diary_entries_internship_id'), table_name='diary_entries')
    op.drop_index(op.f('ix_diary_entries_id'), table_name='diary_entries')
    op.drop_table('diary_entries')
    op.drop_index(op.f('ix_applications_student_id'), table_name='applications')
    op.drop_index(op.f('ix_applications_internship_id'), table_name='applications')
    op.drop_index(op.f('ix_applications_id'), table_name='applications')
    op.drop_table('applications')
    op.drop_index(op.f('ix_user_badges_user_id'), table_name='user_badges')
    op.drop_index(op.f('ix_user_badges_id'), table_name='user_badges')
    op.drop_index(op.f('ix_user_badges_badge_id'), table_name='user_badges')
    op.drop_table('user_badges')
    op.drop_index(op.f('ix_project_teams_lider_id'), table_name='project_teams')
    op.drop_index(op.f('ix_project_teams_id'), table_name='project_teams')
    op.drop_table('project_teams')
    op.drop_index(op.f('ix_portfolios_student_id'), table_name='portfolios')
    op.drop_index(op.f('ix_portfolios_id'), table_name='portfolios')
    op.drop_table('portfolios')
    op.drop_index(op.f('ix_internships_id'), table_name='internships')
    op.drop_index(op.f('ix_internships_company_id'), table_name='internships')
    op.drop_table('internships')
    op.drop_index(op.f('ix_events_organizator_id'), table_name='events')
    op.drop_index(op.f('ix_events_id'), table_name='events')
    op.drop_table('events')
    op.drop_index(op.f('ix_cvs_id'), table_name='cvs')
    op.drop_table('cvs')
    op.drop_index(op.f('ix_certificates_student_id'), table_name='certificates')
    op.drop_index(op.f('ix_certificates_id'), table_name='certificates')
    op.drop_table('certificates')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_badges_id'), table_name='badges')
    op.drop_table('badges')
    # ### end Alembic commands ###
