"""internships beceri_profili alani

Revision ID: f85af9d89381
Revises: cabffb7c6683
Create Date: 2026-05-21 13:39:48.846039

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f85af9d89381'
down_revision: Union[str, Sequence[str], None] = 'cabffb7c6683'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('internships', sa.Column('beceri_profili', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('internships', 'beceri_profili')
    # ### end Alembic commands ###
